spring:
  flyway:
    driver-class-name: org.h2.Driver
    sql-migration-prefix: v
    sql-migration-separator: __
    url: jdbc:h2:mem:authdb
    schemas: flyway
    user: test
    password: test
    validateMigrationNaming: true
  datasource:
    url: jdbc:h2:mem:authdb
    driverClassName: org.h2.Driver
    username: test
    password: test
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console.enable: true


