CREATE TABLE AUTH.AUTH_USER(
     USER_ID                INT PRIMARY KEY,
     USER_NAME              VARCHAR(45) UNIQUE NOT NULL,
     PASSWORD               VARCHAR(512) NOT NULL,
     ACTIVE                 VARCHAR(1) NOT NULL,
     CONFIRMED              VARCHAR(1) NOT NULL,
     INVALID_LOGIN_ATTEMPTS INT NOT NULL,
     LOCKED                 VARCHAR(1) NOT NULL,
     LAST_ACCESS            TIMESTAMP,
     R_CRE_TIME             TIMESTAMP NOT NULL,
     R_MOD_TIME             TIMESTAMP NOT NULL,
     USER_PROFILE_ID        INT
  );

CREATE SEQUENCE AUTH.USER_SEQ START WITH 1 INCREMENT BY 1;
