CREATE TABLE AUTH.USER_PROFILE(
     ID            INT PRIMARY KEY,
     FIRST_NAME    VARCHAR(255) NOT NULL,
     LAST_NAME     VARCHAR(255) NOT NULL,
     MIDDLE_NAME   VARCHAR(255),
     DATE_OF_BIRTH DATE,
     EMAIL         VARCHAR(100),
     PROFILE_IMAGE VARCHAR(100),
     ADDRESS_ID    INT
  );

CREATE SEQUENCE AUTH.USER_PROFILE_SEQ START WITH 1 INCREMENT BY 1;