CREATE TABLE AUTH.ADDRESS(
     ID      INT PRIMARY KEY,
     LINE1   VARCHAR(255),
     LINE2   VARCHAR(255),
     LINE3   VARCHAR(255),
     STATE   VARCHAR(100),
     CITY    VARCHAR(100),
     COUNTRY VARCHAR(100)
  );

CREATE SEQUENCE AUTH.ADDRESS_SEQ START WITH 1 INCREMENT BY 1;